spring:
  application:
    name: jp-other-ms

server:
  port: 8086

#logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
#  tracing:
#    sampling:
#      #      used for tracing
#      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true